export const dataOptions = {
  formulacion: {
    celda_1: [
      {
        id: 1,
        idFamilia: 1,
        sku: "X072",
        familia: "Jamones Granel",
        kg_lote: 1070,
        tipo_rack: "Lunch",
        no_rack_lote: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "EMUL + CYD + SALM",
        emulsion: "PASTA + SALM + CYD",
        tipo_emulsion: "EMUL",
      },
      {
        id: 2,
        idFamilia: 1,
        sku: "X576",
        familia: "Jamones Granel",
        kg_lote: 1070,
        tipo_rack: "Lunch",
        no_rack_lote: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 3,
        idFamilia: 2,
        sku: "CF0126",
        familia: "Jamones Rebanados",
        kg_lote: 1070,
        tipo_rack: "Bala",
        no_rack_lote: 3.5,
        kg_barra: 9.7,
        no_barras: 110,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
    ],
    celda_2: [
      {
        id: 3,
        idFamilia: 1,
        sku: "CF0232",
        familia: "Jamones Granel",
        kg_lote: 3575,
        tipo_rack: "Pinic 5",
        no_rack_lote: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "EMUL + CYD + SALM",
        emulsion: "PASTA + SALM + CYD",
        tipo_emulsion: "EMUL",
      },
      {
        id: 4,
        idFamilia: 1,
        sku: "X438",
        familia: "Jamones Granel",
        kg_lote: 1070,
        tipo_rack: "Lunch",
        no_rack_lote: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
      {
        id: 5,
        idFamilia: 2,
        sku: "10803",
        familia: "Jamones Rebanados",
        kg_lote: 1070,
        tipo_rack: "Bala",
        no_rack_lote: 3.5,
        kg_barra: 9.7,
        no_barras: 110,
        formulacion: "",
        emulsion: "",
        tipo_emulsion: "EMUL",
      },
    ],
  },
  salchichas_granel: {
    maquina_A: [
      {
        id: 6,
        idFamilia: 3,
        sku: "X971",
        familia: "Salchichas Granel",
        kg_lote: 1070,
        tipo_rack: "Lunch",
        no_rack_lote: 1,
        kg_barra: 2.5,
        no_barras: 428,
        formulacion: "-",
        emulsion: "-",
        tipo_emulsion: "-",
      },
      {
        id: 7,
        idFamilia: 3,
        sku: "81128",
        familia: "Salchichas Granel",
        kg_lote: 2200,
        tipo_rack: "-",
        no_rack_lote: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "-",
        emulsion: "-",
        tipo_emulsion: "-",
      },
    ],
    maquina_B: [
      {
        id: 8,
        idFamilia: 3,
        sku: "81135",
        familia: "Salchichas Granel",
        kg_lote: null,
        tipo_rack: "-",
        no_rack_lote: null,
        kg_barra: null,
        no_barras: null,
        formulacion: "-",
        emulsion: "-",
        tipo_emulsion: "-",
      },
    ],
  },
};

export const dataTimings = [
  // "Congelador",
  // "Estación 2 Corte y Deshuese",
  "Estación 3 Salmuerizador 1",
  "Estación 3 Salmuerizador 2",
  "Estación 3 Salmuerizador 3",
  "Estación 3 Viriomix",
  "Estación 4 Emulsiones",
  "Estación 5 Cocimiento",
  "Estación 6 Enfriamiento",
  "Estación 7 Rebanados",
  "Estación 4 Rebanados",
  // "Timepo STD Enfriamiento",
  // "Tiempo STD Desmoldeo",
];
