export const Formulacion = {
  celda_1: [
    {
      sku: "X072",
      familia: "Jamones Granel",
      tamano_lote: 1070,
      tipo_rack: "Lunch",
      no_rack_lote: 1,
      peso_promedio_barra: 2.5,
      cantidad_barras: 428,
      formulacion: "EMUL + CYD + SALM",
      emulsion: "PASTA + SALM + CYD",
      tipo_emulsion: "EMUL",
    },
    {
      sku: "X576",
      familia: "Jamones Granel",
      tamano_lote: 1070,
      tipo_rack: "Lunch",
      no_rack_lote: 1,
      peso_promedio_barra: 2.5,
      cantidad_barras: 428,
      formulacion: "",
      emulsion: "",
      tipo_emulsion: "EMUL",
    },
    {
      sku: "CF0126",
      familia: "Jamones Rebanados",
      tamano_lote: 1070,
      tipo_rack: "Bala",
      no_rack_lote: 3.5,
      peso_promedio_barra: 9.7,
      cantidad_barras: 110,
      formulacion: "",
      emulsion: "",
      tipo_emulsion: "EMUL",
    },
  ],
  celda_2: [
    {
      sku: "CF0232",
      familia: "Jamones Granel",
      tamano_lote: 3575,
      tipo_rack: "Pinic 5",
      no_rack_lote: 1,
      peso_promedio_barra: 2.5,
      cantidad_barras: 428,
      formulacion: "EMUL + CYD + SALM",
      emulsion: "PASTA + SALM + CYD",
      tipo_emulsion: "EMUL",
    },
    {
      sku: "X438",
      familia: "Jamones Granel",
      tamano_lote: 1070,
      tipo_rack: "Lunch",
      no_rack_lote: 1,
      peso_promedio_barra: 2.5,
      cantidad_barras: 428,
      formulacion: "",
      emulsion: "",
      tipo_emulsion: "EMUL",
    },
    {
      sku: "10803",
      familia: "Jamones Rebanados",
      tamano_lote: 1070,
      tipo_rack: "Bala",
      no_rack_lote: 3.5,
      peso_promedio_barra: 9.7,
      cantidad_barras: 110,
      formulacion: "",
      emulsion: "",
      tipo_emulsion: "EMUL",
    },
  ],
};
